# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [49]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [ ]:
import numpy as np
v = np.arange(10,49)
print(v)

4. Find the shape of previous array in question 3

In [ ]:
v.shape

5. Print the type of the previous array in question 3

In [ ]:
v.dtype


6. Print the numpy version and the configuration


In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

7. Print the dimension of the array in question 3


In [ ]:
v.ndim

8. Create a boolean array with all the True values

In [2]:
import numpy as np
bool_arr = np.ones(10, dtype=bool)
print('Numpy Array: ')
print(bool_arr)

Numpy Array: 
[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [ ]:
N = 5
arr = [0 for i in range(N)] 
print(arr) 

10. Create a three dimensional array



In [ ]:
a_3d_array = np.zeros((2, 2, 2))
print(a_3d_array)

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [3]:

arr = [5, 15, 25, 35, 45]
print("Array is :",arr)
 
res = arr[::-1] 
print("Resultant new reversed array:",res)

Array is : [5, 15, 25, 35, 45]
Resultant new reversed array: [45, 35, 25, 15, 5]


12. Create a null vector of size 10 but the fifth value which is 1 

In [4]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [6]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [5]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5]) 
print(arr) 
print(arr.dtype)  
arr = arr.astype('float64') 
print(arr) 
print(arr.dtype) 

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [11]:
import numpy as np
a1 = ([1., 2., 3.,4., 5., 6.]) 
a2 = ([0., 4., 1.,7., 2., 12.])
np.multiply(a1, a2)

array([ 0.,  8.,  3., 28., 10., 72.])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [18]:
import numpy as np 
arr1 = np.array([1., 2., 3., 4., 5., 6.])
arr2 = np.array([0., 4., 1., 7., 2., 12.])
arr1=arr1>arr2


17. Extract all odd numbers from arr with values(0-9)

In [19]:
import numpy as np
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
a[a % 2 == 1]


array([1, 3, 5, 7, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [25]:
import numpy as np
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
a[a % 2 == 1] 
a=[1:1]=0

SyntaxError: invalid syntax (<ipython-input-25-db7187eec286>, line 4)

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [28]:
import numpy as np 
arr = np.arrange(10)
arr [5:-1]= 12
arr

AttributeError: module 'numpy' has no attribute 'arrange'

20. Create a 2d array with 1 on the border and 0 inside

In [29]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [34]:
import numpy as np 
arr2d = np.array([1, 2, 3,

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[2,1]=12

arr2d

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [37]:
import numpy as np 
arr= np.arange(1,6)
arr.reshape (1,1)
arr[64]

ValueError: cannot reshape array of size 5 into shape (1,1)

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [38]:
import numpy as np 
srr=np.arange(0-9)
arr.reshape(3,3)
arr[0]

ValueError: cannot reshape array of size 5 into shape (3,3)

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [42]:
import numpy as np 
srr = np.arange(0,9).reshape(3,3)
arr

arr[1,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
import numpy as np 
array1 = np.arange(12).reshape(4,3)
array1
array1[3][1]
array1[3][2]

26. Create a 10x10 array with random values and find the minimum and maximum values

In [46]:
import numpy as np 
arr = np.random.randint(100,size=(10,10))
arr
print (np.min(arr))
print (np.max(arr))

0
99


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [48]:
import numpy as np 
a = np.array(1,2,3,2,3,4,3,4,5,6)
b = np.array(7,2,10,2,7,4,9,4,9,8)
R = np.intersect1d (a,b)
R


TypeError: array() takes from 1 to 2 positional arguments but 10 were given

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [ ]:
def findMissing(a, b, n, m): 
  
    for i in range(n): 
        for j in range(m): 
            if (a[i] == b[j]): 
                break
  
        if (j == m - 1): 
            print(a[i], end = " ") 
    if __name__ == "__main__": 
      
    a = np.array(1,2,3,2,3,4,3,4,5,6) 
    b = np.array(7,2,10,2,7,4,9,4,9,8)
    n = len(a) 
    m = len(b) 
    findMissing(a, b, n, m) 

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [ ]:
import numpy as np 
names = np.array('Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe') data = np.random.randn(7, 4)
data 
print (data [name !="Will"])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
import numpy as np 
names = np.array('Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe') data = np.random.randn(7, 4)
data 
print (data [name !="Will"])
print (data [name !="Joe"])


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
import numpy as np 
arr = np.radom.randn(1,15).reshape(5,3)
arr

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [ ]:
import numpy as np 
arr = np.random.randn(1,16).reshape(2,2,4)
arr 

33. Swap axes of the array you created in Question 32

In [ ]:
import numpy as np 
data= np.random.randn(1,16).reshape(2,2,4)
data
data.T


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [ ]:
import numpy as np 
R= np.arange(10)
R= np.sqrt(R)
np.where(R<0.5,0,R)

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:
import numpy as np 
a = np.random.randint(12)
b = np.random.randint(12)
np.maximum(a,b)


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
import numpy as np 
names = np.array('Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe')
names
names = set(names)
names

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

result = np.setdiff1d(a, b)
print(result)

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [ ]:
import numpy as np
 
ini_array = numpy.array([34,43,73,82,22,12,53,94,66])
 

print("initial_array : ", str(ini_array));
 

column_to_be_added = numpy.array([10,10,10])
 

result = np.hstack((ini_array, np.atleast_2d(column_to_be_added).T))

print ("resultant array", str(result))

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
import numpy as np 
x = np.array([1., 2., 3., 4., 5., 6.])
y = np.array([6., 23., -1, 7, 8, 9])
>>> x * y

40. Generate a matrix of 20 random values and find its cumulative sum

In [50]:
import numpy as np 
a = np.random.randint(12)
b = np.cumsum(a)
print b

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(b)? (<ipython-input-50-8eba0f89dc02>, line 4)